apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-bottlerocket-demo
  region: ap-southeast-1

nodeGroups:
  # On-Demand instances
  - name: core-bottlerocket
    instanceType: m6g.large
    minSize: 2
    desiredCapacity: 3
    maxSize: 10
    amiFamily: Bottlerocket
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      withAddonPolicies:
        autoScaler: true
        appMesh: true
        albIngress: true
        xRay: true
        externalDNS: true
        certManager: true
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
