apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: secure-eks
  region: ap-southeast-1

vpc:
  id: 'vpc-6905b90e'
  cidr: '10.50.0.0/16'
  subnets:
    private:
      ap-southeast-1a:
        id: 'subnet-01d4555aeb5451f34'
      ap-southeast-1b:
        id: 'subnet-0fadb38729645bac4'
      ap-southeast-1c:
        id: 'subnet-0f215e684b6058329'
    public:
      ap-southeast-1a:
        id: 'subnet-9f4f3bd6'
      ap-southeast-1b:
        id: 'subnet-44bffb23'
      ap-southeast-1c:
        id: 'subnet-50484116'

nodeGroups:
  - name: ng-core
    instancesDistribution:
      instanceTypes: ['t3.small', 't3.large'] # At least two instance types should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    minSize: 2
    maxSize: 8
    volumeSize: 100
    volumeType: gp2
    ssh:
      publicKeyName: eksworkshop
    labels:
      environment: staging
      type: normal
      size: large
      subnet: public
    tags:
      environment: staging
      platform: eks
      subnet: public
      type: normal
    iam:
      withAddonPolicies:
        autoScaler: true
        appMesh: true
        albIngress: true
        xRay: true

  - name: ng-memory
    instanceType: r5.large
    minSize: 2
    maxSize: 8
    desiredCapacity: 2
    ssh:
      publicKeyName: eksworkshop
    labels:
      environment: staging
      type: memory
      size: large
      subnet: public
    tags:
      environment: staging
      platform: eks
      subnet: public
      type: memory
    iam:
      withAddonPolicies:
        autoScaler: true
        appMesh: true
        albIngress: true
        xRay: true

  - name: ng-private-compute
    instanceType: c5.large
    minSize: 2
    maxSize: 8
    desiredCapacity: 2
    ssh:
      publicKeyName: eksworkshop
    privateNetworking: true
    labels:
      environment: staging
      type: compute
      size: large
      subnet: private
    tags:
      environment: staging
      platform: eks
      subnet: private
      type: compute
    iam:
      withAddonPolicies:
        autoScaler: true
        appMesh: true
        albIngress: true
        xRay: true
