apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-ocean
  region: ap-northeast-1

nodeGroups:
- name: ocean-core
  minSize: 2
  maxSize: 10
  desiredCapacity: 2
  volumeSize: 100
  volumeType: gp2
  privateNetworking: true
  labels:
    type: app
    ec2: core
  tags:
    type: app
    ec2: core

  # Enable Ocean integration with custom configuration.
  spotOcean:
    strategy:
      # Percentage of Spot instances that would spin up
      # from the desired capacity.
      spotPercentage: 50

      # Allow Ocean to utilize any available reserved
      # instances first before purchasing Spot instances.
      utilizeReservedInstances: true

      # Launch On-Demand instances in case of no Spot
      # instances available.
      fallbackToOnDemand: true

    autoScaler:
      # Enable the Ocean autoscaler.
      enabled: true

      # Cooldown period between scaling actions.
      cooldown: 300

      # Spare resource capacity management enabling fast
      # assignment of Pods without waiting for new resources
      # to launch.
      headrooms:

        # Number of CPUs to allocate. CPUs are denoted
        # in millicores, where 1000 millicores = 1 vCPU.
      - cpuPerUnit: 500

        # Number of GPUs to allocate.
        gpuPerUnit: 0

        # Amount of memory (MB) to allocate.
        memoryPerUnit: 2048

        # Number of units to retain as headroom, where
        # each unit has the defined CPU and memory.
        numOfUnits: 2
        
    compute:
      instanceTypes:
        # Instance types allowed in the Ocean cluster.
        # Cannot be configured if the blacklist is configured.
        whitelist: # OR blacklist
        - t3.xlarge
        - m5.xlarge
        - m4.xlarge

- name: ocean-reserved
  minSize: 1
  maxSize: 4
  desiredCapacity: 1
  volumeSize: 100
  volumeType: gp2
  privateNetworking: true
  labels:
    type: app
    ec2: reserved
  tags:
    type: app
    ec2: reserved
  iam:
    withAddonPolicies:
      autoScaler: true
      appMesh: true
      albIngress: true
      xRay: true

  # Enable Ocean integration with custom configuration.
  spotOcean:
    strategy:
      spotPercentage: 100
      utilizeReservedInstances: true
      fallbackToOnDemand: false
    autoScaler:
      enabled: true
      cooldown: 180